\input texinfo   @c -*-texinfo-*-

@c %**start of header
@setfilename jcbnfp.info
@settitle jcbnfp
@afourpaper
@documentencoding UTF-8
@documentlanguage en
@finalout
@c %**end of header
@set VERSION 0.3
@set PACKAGE se.kth.maandree.jcbnfp

@copying
This manual is for jcbnfp
(version @value{VERSION}),

Copyright @copyright{} 2012 Mattias Andrée

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts. A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying

@ifnottex
@node Top
@top jcbnfp
@insertcopying
@end ifnottex

@titlepage
@title jcbnfp @value{VERSION}
@subtitle JCBNF parser library for Java
@c ** start of front page image **
@c If print make a pdf or hard copy with the front cover
@c you may or may not want to remove this.
@c@image{infoimage,423.5px}
@c ** end of front page image **
@author by Mattias Andrée (maandree)

@page
@vskip 0pt plus 1filll
@insertcopying
@page
@*@*
@center{Lets make compilers!}
@end titlepage

@contents


@menu
* Overview::                            Brief overview of jcbnfp.
* Testing::                             How to use jcbnfp for testing.
* GNU Free Documentation License::      Copying and sharing this manual.
* Concept index::                       Concept index.
@end menu




@node Overview
@chapter Overview
@cindex overview
@include overview.texinfo


@node Testing
@chapter Testing
@cindex testing
@include testing.texinfo


@node GNU Free Documentation License
@appendix GNU Free Documentation License
@include fdl.texinfo


@node Concept index
@appendix Concept index
@printindex cp


@bye

